### ISSUE TITLE
Invalid base32 character

### ISSUE THREAD

**Issue by petergCA** [samrum/OnStarJS#263]
Hello, I'm getting the following in the log when trying to setup the add-on. I am not sure what is the issue here. Thanks in advance for any help!

Authentication failed: Error: Invalid base32 character in key
    at TOTP.base32tohex (/app/node_modules/onstarjs2/dist/index.cjs:34421:23)
    at TOTP.generate (/app/node_modules/onstarjs2/dist/index.cjs:34397:32)
    at GMAuth.<anonymous> (/app/node_modules/onstarjs2/dist/index.cjs:34535:34)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/onstarjs2/dist/index.cjs:43:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error: Main function error: {"error":{"message":"Invalid base32 character in key"},"timestamp":"2024-12-02 14:52:29"}

**Comment by b3tts32** [comment]
Getting the same error

**Comment by petergCA** [comment]
After the update today, this error has changed to the following:
`error: Main function error: {"error":{"message":"Provided TOTP Key does not meet expected key length. Key should be 16 alphanumeric characters."},"timestamp":"2024-12-04 10:20:46"}`
Would appreciate some help in resolving if possible. Thanks!

**Comment by petergCA** [comment]
Got it. Thanks @BigThunderSR, I misinterpreted the instructions in setup. Seems like its working for me now. Much appreciated.
